# Generated by Django 3.1.1 on 2020-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqs_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
