# Generated by Django 3.1.1 on 2020-09-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muqs_qr', '0002_auto_20200924_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='slug',
        ),
    ]
